---
title: "Group 02 UCSB domestic grad enrollment"
author: "Chelsie McWhorter & Kort Alexander"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)

```

```{r}
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```

```{r}
ggplot(ucsb_grad, aes(x = year_abbr, y = domestic_enrollment)) +
  geom_col(aes(fill = ethnicity), position = "fill") +
  labs(x = "Academic Year",
       y= "Proportion of Domestic Student Enrollment",
       title = "UCSB Domestic Enrollment by Ethnicity, 2008-2019") +
  theme_minimal()
```

**Figure 1** Domestic student enrollment at UCSB has grown more diverse over time.
<<<<<<< HEAD:Group 02 UCSB domestic grad enrollment.Rmd

*Data source: UCSB Office of Budget and Planning, https://bap.ucsb.edu/institutional-research/campus-profiles*
=======
>>>>>>> 9037ef3547ae8eeccd371c657dec38686b6764ec:group_02_ucsb_grad.Rmd
